using System;
using System.Collections.Generic;
using System.Text;

namespace RAMMS.Domain.Models
{
    public class FormDownloadHeader
    {
        public string header1 { get; set; }
        public string header2 { get; set; }
        public string header3 { get; set; }
        public string header4 { get; set; }
        public string header5 { get; set; }
        public string header6 { get; set; }
        public string header7 { get; set; }
        public string header8 { get; set; }
        public string header9 { get; set; }
        public string header10 { get; set; }
        public string header11 { get; set; }
        public string header12 { get; set; }
        public string header13 { get; set; }
        public string header14 { get; set; }
        public string header15 { get; set; }
        public string header16 { get; set; }
        public string header17 { get; set; }
        public string header18 { get; set; }
        public string header19 { get; set; }
        public string header20 { get; set; }
        public string header21 { get; set; }
        public string header22 { get; set; }
        public string header23 { get; set; }
        public string header24 { get; set; }
        public string header25 { get; set; }
        public string header26 { get; set; }
        public string header27 { get; set; }
        public string header28 { get; set; }
        public string header29 { get; set; }
        public string header30 { get; set; }
        public string header31 { get; set; }
        public string header32 { get; set; }
        public string header33 { get; set; }
        public string header34 { get; set; }
        public string header35 { get; set; }
        public string header36 { get; set; }
        public string header37 { get; set; }
        public string header38 { get; set; }
        public string header39 { get; set; }
        public string header40 { get; set; }
        public string header41 { get; set; }
        public string header42 { get; set; }
        public string header43 { get; set; }
        public string header44 { get; set; }
        public string header45 { get; set; }
        public string header46 { get; set; }
        public string header47 { get; set; }
        public string header48 { get; set; }
        public string header49 { get; set; }
        public string header50 { get; set; }
        public string header51 { get; set; }
        public string header52 { get; set; }
        public string header53 { get; set; }
        public string header54 { get; set; }
        public string header55 { get; set; }
        public string header56 { get; set; }
        public string header57 { get; set; }
        public string header58 { get; set; }
        public string header59 { get; set; }
        public string header60 { get; set; }
        public string header61 { get; set; }
        public string header62 { get; set; }
        public string header63 { get; set; }
        public string header64 { get; set; }
        public string header65 { get; set; }
        public string header66 { get; set; }
        public string header67 { get; set; }
        public string header68 { get; set; }
        public string header69 { get; set; }
        public string header70 { get; set; }
        public string header71 { get; set; }
        public string header72 { get; set; }
        public string header73 { get; set; }
        public string header74 { get; set; }
        public string header75 { get; set; }
        public string header76 { get; set; }
        public string header77 { get; set; }
        public string header78 { get; set; }
        public string header79 { get; set; }
        public string header80 { get; set; }
        public string header81 { get; set; }
        public string header82 { get; set; }
        public string header83 { get; set; }
        public string header84 { get; set; }
        public string header85 { get; set; }
        public string header86 { get; set; }
        public string header87 { get; set; }
        public string header88 { get; set; }
        public string header89 { get; set; }
        public string header90 { get; set; }
        public string header91 { get; set; }
        public string header92 { get; set; }
        public string header93 { get; set; }
        public string header94 { get; set; }
        public string header95 { get; set; }
        public string header96 { get; set; }
        public string header97 { get; set; }
        public string header98 { get; set; }
        public string header99 { get; set; }
        public string header100 { get; set; }

        public string header101 { get; set; }
        public string header102 { get; set; }
        public string header103 { get; set; }
        public string header104 { get; set; }
        public string header105 { get; set; }
        public string header106 { get; set; }
        public string header107 { get; set; }
        public string header108 { get; set; }
        public string header109 { get; set; }
        public string header110 { get; set; }
        public string header111 { get; set; }
        public string header112 { get; set; }
        public string header113 { get; set; }
        public string header114 { get; set; }
        public string header115 { get; set; }
        public string header116 { get; set; }
        public string header117 { get; set; }
        public string header118 { get; set; }
        public string header119 { get; set; }
        public string header120 { get; set; }
        public string header121 { get; set; }
        public string header122 { get; set; }
        public string header123 { get; set; }
        public string header124 { get; set; }
        public string header125 { get; set; }
        public string header126 { get; set; }
        public string header127 { get; set; }
        public string header128 { get; set; }
        public string header129 { get; set; }
        public string header130 { get; set; }
        public string header131 { get; set; }
        public string header132 { get; set; }
        public string header133 { get; set; }
        public string header134 { get; set; }
        public string header135 { get; set; }
        public string header136 { get; set; }
        public string header137 { get; set; }
        public string header138 { get; set; }
        public string header139 { get; set; }
        public string header140 { get; set; }
        public string header141 { get; set; }
        public string header142 { get; set; }
        public string header143 { get; set; }
        public string header144 { get; set; }
        public string header145 { get; set; }
        public string header146 { get; set; }
        public string header147 { get; set; }
        public string header148 { get; set; }
        public string header149 { get; set; }
        public string header150 { get; set; }

        public string header151 { get; set; }

        public string header152 { get; set; }

        public string header153 { get; set; }


        public string header154 { get; set; }

        public string header155 { get; set; }

        public string header156 { get; set; }

        public string header157 { get; set; }

        public string header158 { get; set; }

        public string header159 { get; set; }
        public string header160 { get; set; }
        public string header161 { get; set; }
        public string header162 { get; set; }
        public string header163 { get; set; }
        public string header164 { get; set; }
        public string header165 { get; set; }
        public string header166 { get; set; }
        public string header167 { get; set; }
        public string header168 { get; set; }
        public string header169 { get; set; }
        public string header170 { get; set; }
        public string header171 { get; set; }
        public string header172 { get; set; }
        public string header173 { get; set; }
        public string header174 { get; set; }
        public string header175 { get; set; }
        public string header176 { get; set; }
        public string header177 { get; set; }
        public string header178 { get; set; }
        public string header179 { get; set; }
        public string header180 { get; set; }
        public string header181 { get; set; }
        public string header182 { get; set; }
        public string header183 { get; set; }
        public string header184 { get; set; }
        public string header185 { get; set; }
        public string header186 { get; set; }
        public string header187 { get; set; }
        public string header188 { get; set; }
        public string header189 { get; set; }
        public string header190 { get; set; }
        public string header191 { get; set; }
        public string header192 { get; set; }
        public string header193 { get; set; }
        public string header194 { get; set; }
        public string header195 { get; set; }
        public string header196 { get; set; }
        public string header197 { get; set; }
        public string header198 { get; set; }
        public string header199 { get; set; }
        public string header200 { get; set; }
        public string header201 { get; set; }
        public string header202 { get; set; }
        public string header203 { get; set; }
        public string header204 { get; set; }
        public string header205 { get; set; }
        public string header206 { get; set; }
        public string header207 { get; set; }
        public string header208 { get; set; }
        public string header209 { get; set; }
        public string header210 { get; set; }
        public string header211 { get; set; }
        public string header212 { get; set; }
        public string header213 { get; set; }
        public string header214 { get; set; }
        public string header215 { get; set; }
        public string header216 { get; set; }
        public string header217 { get; set; }
        public string header218 { get; set; }
        public string header219 { get; set; }
        public string header220 { get; set; }
        public string header221 { get; set; }
        public string header222 { get; set; }
        public string header223 { get; set; }
        public string header224 { get; set; }
        public string header225 { get; set; }
        public string header226 { get; set; }
        public string header227 { get; set; }
        public string header228 { get; set; }
        public string header229 { get; set; }
        public string header230 { get; set; }
        public string header231 { get; set; }
        public string header232 { get; set; }
        public string header233 { get; set; }
        public string header234 { get; set; }
        public string header235 { get; set; }
        public string header236 { get; set; }
        public string header237 { get; set; }
        public string header238 { get; set; }
        public string header239 { get; set; }
        public string header240 { get; set; }
        public string header241 { get; set; }
        public string header242 { get; set; }
        public string header243 { get; set; }
        public string header244 { get; set; }
        public string header245 { get; set; }
        public string header246 { get; set; }
        public string header247 { get; set; }
        public string header248 { get; set; }
        public string header249 { get; set; }
        public string header250 { get; set; }
        public string header251 { get; set; }
        public string header252 { get; set; }
        public string header253 { get; set; }
        public string header254 { get; set; }
        public string header255 { get; set; }
        public string header256 { get; set; }
        public string header257 { get; set; }
        public string header258 { get; set; }
        public string header259 { get; set; }
        public string header260 { get; set; }
        public string header261 { get; set; }
        public string header262 { get; set; }
        public string header263 { get; set; }
        public string header264 { get; set; }
        public string header265 { get; set; }
        public string header266 { get; set; }
        public string header267 { get; set; }
        public string header268 { get; set; }
        public string header269 { get; set; }
        public string header270 { get; set; }
        public string header271 { get; set; }
        public string header272 { get; set; }
        public string header273 { get; set; }
        public string header274 { get; set; }
        public string header275 { get; set; }
        public string header276 { get; set; }
        public string header277 { get; set; }
        public string header278 { get; set; }
        public string header279 { get; set; }
        public string header280 { get; set; }
        public string header281 { get; set; }
        public string header282 { get; set; }
        public string header283 { get; set; }
        public string header284 { get; set; }
        public string header285 { get; set; }
        public string header286 { get; set; }
        public string header287 { get; set; }
        public string header288 { get; set; }
        public string header289 { get; set; }
        public string header290 { get; set; }
        public string header291 { get; set; }
        public string header292 { get; set; }
        public string header293 { get; set; }
        public string header294 { get; set; }
        public string header295 { get; set; }
        public string header296 { get; set; }
        public string header297 { get; set; }
        public string header298 { get; set; }
        public string header299 { get; set; }
        public string header300 { get; set; }
        public string header301 { get; set; }
        public string header302 { get; set; }
        public string header303 { get; set; }
        public string header304 { get; set; }
        public string header305 { get; set; }
        public string header306 { get; set; }
        public string header307 { get; set; }
        public string header308 { get; set; }
        public string header309 { get; set; }
        public string header310 { get; set; }
        public string header311 { get; set; }
        public string header312 { get; set; }
        public string header313 { get; set; }
        public string header314 { get; set; }
        public string header315 { get; set; }
        public string header316 { get; set; }
        public string header317 { get; set; }
        public string header318 { get; set; }
        public string header319 { get; set; }
        public string header320 { get; set; }
        public string header321 { get; set; }
        public string header322 { get; set; }
        public string header323 { get; set; }
        public string header324 { get; set; }
        public string header325 { get; set; }


    }
}
